### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by SubhamTyagi** [SubhamTyagi/AppLock#11]
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:888)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:867)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
	at com.lzx.lock.module.lock.GestureUnlockActivity$2.onPreDraw(Unknown Source)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2249)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1298)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6437)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
	at android.view.Choreographer.doCallbacks(Choreographer.java:688)
	at android.view.Choreographer.doFrame(Choreographer.java:623)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
---------END-----------

Device Information

APP.VERSION : 2
VERSION.RELEASE : 7.1.2
VERSION.INCREMENTAL : V10.1.1.0.NAMMIFI
VERSION.SDK.NUMBER : 25
BRAND : Xiaomi
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : N2G47H
MANUFACTURER : Xiaomi
MODEL : Redmi 4
PRODUCT : santoni

**Comment by bushrang3r** [comment]
Me too. Still crashing with this new version (1.0.1)

Device:
Samsung Galaxy Note 4 - Oreo 8.1 (Ressurection Rom)

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/AppLock/blob/81a7ed623a47f8ce8f5c0fe183838235896c91f9/app/src/main/java/com/lzx/lock/activities/lock/GestureUnlockActivity.java#L132.

**Comment by SubhamTyagi** [comment]
java.lang.IllegalArgumentException: width and height must be > 0
	
at
 android.graphics.Bitmap.createBitmap(Bitmap.java:888)

at
 android.graphics.Bitmap.createBitmap(Bitmap.java:867)
	
at
 android.graphics.Bitmap.createBitmap(Bitmap.java:834)

at
 com.lzx.lock.utils.LockUtil.blur(LockUtil.java:137)

at
 com.lzx.lock.activities.lock.GestureUnlockActivity$2.onPreDraw(GestureUnlockActivity.java:133)

---------END-----------
