### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Janekiwie** [SubhamTyagi/AppLock#22]
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:877)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
	at com.lzx.lock.utils.LockUtil.blur(LockUtil.java:137)
	at com.lzx.lock.activities.lock.GestureUnlockActivity$2.onPreDraw(GestureUnlockActivity.java:133)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
---------END-----------

Device Information

APP.VERSION : 4
VERSION.RELEASE : 7.1.2
VERSION.INCREMENTAL : e0d6ab2e56
VERSION.SDK.NUMBER : 25
BRAND : Samsung
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : lineage_zerofltexx-userdebug 7.1.2 NJH47F e0d6ab2e56
MANUFACTURER : samsung
MODEL : SM-G920F
PRODUCT : zerofltexx

**Comment by SubhamTyagi** [comment]
#11
